/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EntryDateRouteImport } from './routes/entry.$date'
import { Route as NotebookIdIndexRouteImport } from './routes/notebook.$id.index'
import { Route as NotebookIdEntryDateRouteImport } from './routes/notebook.$id.entry.$date'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EntryDateRoute = EntryDateRouteImport.update({
  id: '/entry/$date',
  path: '/entry/$date',
  getParentRoute: () => rootRouteImport,
} as any)
const NotebookIdIndexRoute = NotebookIdIndexRouteImport.update({
  id: '/notebook/$id/',
  path: '/notebook/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const NotebookIdEntryDateRoute = NotebookIdEntryDateRouteImport.update({
  id: '/notebook/$id/entry/$date',
  path: '/notebook/$id/entry/$date',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/entry/$date': typeof EntryDateRoute
  '/notebook/$id/': typeof NotebookIdIndexRoute
  '/notebook/$id/entry/$date': typeof NotebookIdEntryDateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/entry/$date': typeof EntryDateRoute
  '/notebook/$id': typeof NotebookIdIndexRoute
  '/notebook/$id/entry/$date': typeof NotebookIdEntryDateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/entry/$date': typeof EntryDateRoute
  '/notebook/$id/': typeof NotebookIdIndexRoute
  '/notebook/$id/entry/$date': typeof NotebookIdEntryDateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/entry/$date' | '/notebook/$id/' | '/notebook/$id/entry/$date'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/entry/$date' | '/notebook/$id' | '/notebook/$id/entry/$date'
  id:
    | '__root__'
    | '/'
    | '/entry/$date'
    | '/notebook/$id/'
    | '/notebook/$id/entry/$date'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EntryDateRoute: typeof EntryDateRoute
  NotebookIdIndexRoute: typeof NotebookIdIndexRoute
  NotebookIdEntryDateRoute: typeof NotebookIdEntryDateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entry/$date': {
      id: '/entry/$date'
      path: '/entry/$date'
      fullPath: '/entry/$date'
      preLoaderRoute: typeof EntryDateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notebook/$id/': {
      id: '/notebook/$id/'
      path: '/notebook/$id'
      fullPath: '/notebook/$id/'
      preLoaderRoute: typeof NotebookIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notebook/$id/entry/$date': {
      id: '/notebook/$id/entry/$date'
      path: '/notebook/$id/entry/$date'
      fullPath: '/notebook/$id/entry/$date'
      preLoaderRoute: typeof NotebookIdEntryDateRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EntryDateRoute: EntryDateRoute,
  NotebookIdIndexRoute: NotebookIdIndexRoute,
  NotebookIdEntryDateRoute: NotebookIdEntryDateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
